### ISSUE TITLE
'/usr/bin/ld: cannot find -lxml2' error

### ISSUE THREAD

**Issue by eunseooong** [seokhyeonhong/aPyOpenGL#3]
When executing `bash install.sh`, following error occurs in the middle of installing fbxsdk.

```shell
/usr/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
make: *** [Makefile:37: fbx.so] Error 1
```

**Comment by seokhyeonhong** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-05-29T20:51:48
          
          
            * 메일 제목 : 
[seokhyeonhong/aPyOpenGL] '/usr/bin/ld: cannot find -lxml2' error (Issue #3)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by eunseooong** [comment]
Needed to run the following code myself with sudo:
```shell
sudo apt-get install libxml2
sudo apt-get install libxml2-dev
``` 
After installing, when I run `bash install.sh`, activate created conda env, and run example, it worked!
Thank you for your help!

**Comment by seokhyeonhong** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-05-29T20:54:56
          
          
            * 메일 제목 : 
Re: [seokhyeonhong/aPyOpenGL] '/usr/bin/ld: cannot find -lxml2' error (Issue #3)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
